---
 - hosts: 127.0.0.1
   become: true
   tasks:
           - name: Generate new account
             shell: ts-node ../../resources/typescript/account/createAccount.ts
           - name: Opening An Account Wallet
             shell: ./../shell/openAnAccountWallet.sh
           - name: Get account info
             shell: ts-node ../../resources/typescript/account/getAccountInfo.ts
           - name: Register Namespace
             shell: ts-node ../../resources/typescript/namespace/registerNamespace.ts
           - name: Get account info
             shell: ts-node ../../resources/typescript/account/getAccountInfo.ts